// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA67dOWWQgtjhZxxfiq7LqfSmoNi4BtMVg',
    appId: '1:442428744110:web:b1080c4441aac723b5a83f',
    messagingSenderId: '442428744110',
    projectId: 'cinematic-yasso-2025-b507b',
    authDomain: 'cinematic-yasso-2025-b507b.firebaseapp.com',
    databaseURL: 'https://cinematic-yasso-2025-b507b-default-rtdb.firebaseio.com',
    storageBucket: 'cinematic-yasso-2025-b507b.firebasestorage.app',
    measurementId: 'G-GK8PZK7XDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7gUCCr_mdIRkJgQyPyXQ1mWtGMxx0PrQ',
    appId: '1:442428744110:android:cc26d9e6560432d9b5a83f',
    messagingSenderId: '442428744110',
    projectId: 'cinematic-yasso-2025-b507b',
    databaseURL: 'https://cinematic-yasso-2025-b507b-default-rtdb.firebaseio.com',
    storageBucket: 'cinematic-yasso-2025-b507b.firebasestorage.app',
  );
}
